name: Build and Test React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: flagexplorerappkc.client  # Set working directory globally

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug File Structure
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test # Or your test command

      - name: Build
        run: npm run build
