name: Build and Package React + .NET API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # **Build React Frontend**
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: flagexplorerappkc.client

      - name: Run Tests
        run: npm test
        working-directory: flagexplorerappkc.client
        continue-on-error: true

      - name: Build
        run: npm run build
        working-directory: flagexplorerappkc.client

      # **Build .NET API Backend (flagexplorerappkc.api)**
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build .NET API
        run: dotnet build --no-restore

      - name: Debug folder structure
        run: ls -ld

      # **Merge React into .NET API**
      - name: Copy React Build to .NET API
        run: |
          rm -rf wwwroot
          mkdir -p wwwroot
          cp -r flagexplorerappkc.client/dist/* wwwroot/

      # **Package for Deployment**
      - name: Publish .NET API
        run: dotnet publish --configuration Release --output packaged-app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app
          path: packaged-app
